@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzgyNTYxNTQyLCJpYXQiOjE3ODI1NTk3NDIsImp0aSI6Ijk0OTlmNmFkNmNkYTQ0NzRiZjNmODI4OWYwZjczYTY4IiwidXNlcl9pZCI6IjIifQ.nyuVsMlB5-JBLH4SodyQ4j_juA0ywlCCyPXmj6EJG8E
###
Curl -X POST http://localhost:8000/api/auth/register/ \
  -H "Content-Type: application/json" \
  -d '{
    "username": "testuser",
    "email": "testuser@example.com",
    "password": "testpassword123"
  }'

###

curl -X POST http://localhost:8000/api/community/posts/ \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer {{token}}" \
  -d '{
    "title": "My first post",
    "content": "Hello world from curl",
    "media_files": []
  }'

###

curl -X POST http://localhost:8000/api/community/posts/4/comments/ \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer {{token}}" \
  -d '{
    "title": "My first post",
    "post": 2,
    "content": "Hello world from curl",
    "media_files": []
  }'

###

curl -X POST http://localhost:8000/api/auth/login/ \
  -H "Content-Type: application/json" \
  -d '{
    "username": "test",
    "password": "12341234"
  }'

###

curl -X GET http://localhost:8000/api/community/posts/4/comments \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer {{token}}"


###

curl -X GET http://localhost:8000/api/community/reports/ \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer {{token}}"


###

curl -X GET http://localhost:8000/api/community/posts/1/ \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer {{token}}"

###

curl -X POST http://localhost:8000/api/community/posts/2/comments/ \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer {{token}}" \
  -d '{
    "content": "This is a test comment"
  }'

###

curl -X POST http://localhost:8000/api/community/posts/4/comments/ \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer {{token}}" \
  -d '{
    "content": "This is a reply",
    "parent_comment": 1
  }'

###

curl -X PUT http://localhost:8000/api/community/comments/4/ \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer {{token}}" \
  -d '{
    "content": "Edited comment text"
  }'

###

curl -X DELETE http://localhost:8000/api/community/comments/2/ \
  -H "Authorization: Bearer {{token}}"

###

curl -X POST http://localhost:8000/api/community/comments/1/like/ \
  -H "Authorization: Bearer {{token}}"


###

curl -X DELETE http://localhost:8000/api/community/comments/1/like/ \
  -H "Authorization: Bearer {{token}}" \
  -d '{
    "report_type": "spam",
    "reason": "This comment is spam"
  }'

###

curl -X POST http://localhost:8000/api/community/comments/1/report/ \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer {{token}}" \
  -d '{
    "report_type": "spam",
    "reason": "This comment is spam"
  }'

###

curl -X POST http://localhost:8000/api/community/posts/1/report/ \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer {{token}}" \
  -d '{
    "report_type": "spam",
    "reason": "This comment is spam"
  }'

###

curl -X PATCH http://localhost:8000/api/community/reports/3/ \
  -H "Content-Type: application/json" \
  -H "Authorization: Bearer {{token}}" \
  -d '{
    "action": ""
  }'

###

curl -X GET http://localhost:8000/api/users/2/reviews/ \
  -H "Authorization: Bearer {{token}}"

###

curl -X GET http://localhost:8000/api/users/2/activity/ \
  -H "Authorization: Bearer {{token}}"

###

curl -X GET http://localhost:8000/api/users/2/followers/ \
  -H "Authorization: Bearer {{token}}"

###

curl -X GET http://localhost:8000/api/users/2/following/ \
  -H "Authorization: Bearer {{token}}"

###

curl -X POST http://localhost:8000/api/users/2/follow/ \
  -H "Authorization: Bearer {{token}}"

###

curl -X DELETE http://localhost:8000/api/users/2/follow/ \
  -H "Authorization: Bearer {{token}}"

###

curl -X GET  http://localhost:8000/api/users/profile/7/ \
  -H "Authorization: Bearer {{token}}"
