# Generated by Django 4.2.30 on 2026-05-14 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post', 'created_at'], name='community_c_post_id_bea033_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['parent_comment', 'created_at'], name='community_c_parent__61896d_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['follower'], name='community_f_followe_e95289_idx'),
        ),
        migrations.AddIndex(
            model_name='follow',
            index=models.Index(fields=['following'], name='community_f_followi_5ff31f_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='community_p_created_6febb2_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-like_count'], name='community_p_like_co_a023de_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['is_hidden', '-created_at'], name='community_p_is_hidd_12be74_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['status', '-created_at'], name='community_r_status_9e80af_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingpost',
            index=models.Index(fields=['-score'], name='community_t_score_19ac6d_idx'),
        ),
        migrations.AddIndex(
            model_name='trendingpost',
            index=models.Index(fields=['-calculated_at'], name='community_t_calcula_3dda83_idx'),
        ),
    ]
