# Generated by Django 4.2.30 on 2026-06-17 18:05
# flake8: noqa
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0008_alter_mediainteraction_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CFModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=40, unique=True)),
                ('model_data', models.BinaryField()),
                ('user_count', models.IntegerField()),
                ('item_count', models.IntegerField()),
                ('latent_dim', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'get_latest_by': 'created_at',
            },
        ),
        migrations.CreateModel(
            name='UserEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(verbose_name=768)),
                ('source_media_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMediaScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media.media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'media')},
            },
        ),
        migrations.CreateModel(
            name='MediaEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', pgvector.django.vector.VectorField(dimensions=768)),
                ('source_text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='media.media')),
            ],
            options={
                'indexes': [pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['embedding'], m=16, name='media_embedding_hnsw_idx', opclasses=['vector_cosine_ops'])],
            },
        ),
    ]
