# Generated by Django 4.2.30 on 2026-06-20 09:03
# flake8: noqa
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_delete_usermediascore'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='mediaembedding',
            constraint=models.UniqueConstraint(fields=('media',), name='unique_media_embedding'),
        ),
    ]
