# Generated by Django 4.2.30 on 2026-06-21 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0003_mediaembedding_unique_media_embedding'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='mediaembedding',
            name='unique_media_embedding',
        ),
    ]
