# Generated by Django 4.2.30 on 2026-06-23 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0005_remove_mediaembedding_unique_media_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='cfmodel',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
    ]
