# Generated by Django 4.2.30 on 2026-04-24 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                                           primary_key=True, serialize=False,
                                           verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('media_type', models.CharField(choices=[('movie', 'Movie'),
                                                         ('anime', 'Anime'),
                                                         ('drama', 'Drama')],
                                                max_length=10)),
                ('country', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('director', models.CharField(blank=True, max_length=100)),
                ('cast', models.TextField(blank=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('image_url', models.URLField()),
                ('avg_rating', models.FloatField(default=0)),
                ('rating_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MediaInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('action', models.CharField(choices=[('like', 'Likes'),
                                                     ('dislike', 'Dislike'),
                                                     ('watchlist',
                                                      'Watchlist')],
                                            max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True,
                                           serialize=False,
                                           verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3),
                                                        (4, 4), (5, 5)])),
                ('content', models.TextField()),
                ('images', models.JSONField(default=list)),
                ('visibility', models.CharField(choices=[('public', 'Public'),
                                                         ('followers',
                                                          'Followers only'),
                                                         ('private',
                                                         'Private')],
                                                default='public',
                                                max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('media', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reviews', to='media.media')),
            ],
        ),
    ]
