# Generated by Django 4.2.30 on 2026-04-24 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reviews',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mediainteraction',
            name='media',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='interactions',
                to='media.media'),
        ),
        migrations.AddField(
            model_name='mediainteraction',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='interactions',
                to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='media',
            name='genres',
            field=models.ManyToManyField(related_name='media_items',
                                         to='media.genre'),
        ),
        migrations.AddField(
            model_name='genre',
            name='interested_users',
            field=models.ManyToManyField(blank=True,
                                         related_name='favorite_genres',
                                         to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='review',
            unique_together={('user', 'media')},
        ),
        migrations.AlterUniqueTogether(
            name='mediainteraction',
            unique_together={('user', 'media')},
        ),
    ]
