# Generated by Django 4.2.30 on 2026-04-26 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='interested_users',
        ),
    ]
