# Generated by Django 4.2.30 on 2026-05-15 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_remove_genre_interested_users'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['media_type', '-avg_rating'], name='media_media_media_t_e0b9c6_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['country', 'media_type'], name='media_media_country_afddaf_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['-created_at'], name='media_media_created_9df1bb_idx'),
        ),
        migrations.AddIndex(
            model_name='mediainteraction',
            index=models.Index(fields=['user', 'action'], name='media_media_user_id_a938c6_idx'),
        ),
        migrations.AddIndex(
            model_name='mediainteraction',
            index=models.Index(fields=['media', 'action'], name='media_media_media_i_29bcd1_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['media', '-created_at'], name='media_revie_media_i_f2d3eb_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['user', '-created_at'], name='media_revie_user_id_07d0c5_idx'),
        ),
    ]
