# Generated by Django 4.2.30 on 2026-05-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_media_media_media_media_t_e0b9c6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='external_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='media',
            name='external_source',
            field=models.CharField(default='manual', max_length=20),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['external_source', 'external_id'], name='media_media_externa_03aba6_idx'),
        ),
        migrations.AddConstraint(
            model_name='media',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id__gt', '')), fields=('external_source', 'external_id'), name='unique_media_external_source_id'),
        ),
    ]
