# Generated by Django 4.2.30 on 2026-06-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_media_external_id_media_external_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='age_rating',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
