# Generated by Django 4.2.30 on 2026-06-12 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_media_age_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='language',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='media',
            name='runtime',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='media',
            name='side_poster_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
