# Generated by Django 4.2.30 on 2026-06-15 08:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('media', '0007_media_language_media_runtime_media_side_poster_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mediainteraction',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='mediainteraction',
            name='action',
            field=models.CharField(choices=[('like', 'Likes'), ('dislike', 'Dislike'), ('watchlist', 'Watchlist'), ('watched', 'Watched')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='mediainteraction',
            unique_together={('user', 'media', 'action')},
        ),
    ]
