# Generated by Django 4.2.30 on 2026-05-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='chatroommember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'),
                                            ('moderator', 'Moderator'),
                                            ('member', 'Member')],
                                   default='member', max_length=10),
        ),
    ]
